[build]
  command = "npm run build"
  publish = ".next"

[plugins]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]