[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs@4.39.0"
  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200