import "./globals.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import { Poppins } from "next/font/google";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import Whatsapp from "./Components/Whatsapp";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Explicitly set metadataBase to avoid Next.js warning during build
  metadataBase: new URL("http://localhost:3000"),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="font-main">
        <Header />
        <Whatsapp />
        {children}
        <Footer />
      </body>
    </html>
  );
}
